<?php

$dbcon= DatabaseContext::dbConnect();//DatabaseContext
$s = new Ncoer();
$ncoers = $s->getAllNcoers(DatabaseContext::dbConnect());
?>


<html lang="en">

<body>
<h2 class="report-title">NCOER Report</h2>
<div class="m-1">
    <!--    Displaying Data in Table-->
    <table class="table table-bordered tbl">
        <thead>
        <tr>
            <th scope="col">NCOER_ID</th><!--//The individual oer ID-->
            <th scope="col">Rank </th><!--generated by USER table.Rank-->
            <th scope="col">First Name</th><!--generated by USER table.FirstName-->
            <th scope="col">Last Name</th><!--generated by USER table.LastName-->
            <th scope="col">Rater</th><!--Who is writing OER, Varchar for now-->
            <th scope="col">Senior Rater</th><!--reviewer name , work-->
            <th scope="col">Reviewer</th><!--Who is signing off on oer-->
            <th scope="col">Last NCOER</th><!--Date-->
            <th scope="col">THRU Date</th><!--Count Down to due date-->
            <th scope="col">Due</th><!--Due-->
            <th scope="col">Type</th><!--Type of OER-->
            <th scope="col">Remarks</th><!--Notes-->
        </tr>
        </thead>
        <tbody>
        <!--This Will be a for each loop to generate the rows & buttons-->
        <?php foreach ($ncoers as $ncoer) { ?>
            <tr>
                <!--$id, $user_id, $rank, $rater,
                 $int_rater, $senior_rater, $last_oer, $thru_date, $due, $type, $remarks-->
                <th><?= $ncoer->id; ?></th>
                <th><?= $ncoer->rank; ?></th>
                <th><?= $ncoer->first_name; ?></th><!--generated by USER table.FirstName-->
                <th><?= $ncoer->last_name; ?></th><!--generated by USER table.LastName-->
                <th><?= $ncoer->rater; ?></th>
                <th><?= $ncoer->senior_rater; ?></th>
                <th><?= $ncoer->reviewer; ?></th>
                <th><?= $ncoer->last_ncoer; ?></th>
                <th><?= $ncoer->thru_date; ?></th>
                <th><?= $ncoer->due; ?></th>
                <th><?= $ncoer->type; ?></th>
                <th><?= $ncoer->remarks; ?></th>


                <!--UPDATE AND DELETE BUTTONS-->
                <td>
                    <form action="../Pages/NCOER/updateNCOER.php" method="post">
                        <input type="hidden" name="id" value="<?= $ncoer->id;?>"/>
                        <input type="submit" class="button btn btn-primary" name="updateNcoer" value="Update"/>
                    </form>
                </td>
                <td>
                    <form action="../Pages/NCOER/deleteNCOER.php" method="post">
                        <input type="hidden" name="id" value="<?= $ncoer->id; ?>"/>
                        <input type="submit" class="button btn btn-danger" name="deleteNCOER" value="Delete"/>
                    </form>
                </td>
            </tr>

        <?php } ?>
        </tbody>
    </table>
    <a href="../Pages/NCOER/addNCOER.php" id="btn_addNCOER" class="btn btn-success btn-lg float-right">Add NCOER</a>
    <br>
    <br>
    <br>
</div>
</body>
</html>


<!--//create button to update the table
//create button to delete table
//create button to add to table
//ASIA LEVESQUE-->