<?php
//includes come from OER page

?>
<html lang="en">


<body>
<h2 class="report-title">OER Report</h2>
<div class="m-1">
    <!--    Displaying Data in Table-->
    <table class="table table-bordered tbl">
        <thead>
        <tr>
            <th scope="col">OER_ID</th><!--//The individual oer ID-->
            <th scope="col">Rank </th><!--generated by USER table.Rank-->
            <th scope="col">First Name</th><!--generated by USER table.FirstName-->
            <th scope="col">Last Name</th><!--generated by USER table.LastName-->
            <th scope="col">Rater</th><!--Who is writing OER, Varchar for now-->
            <th scope="col">Int Rater</th><!--Who is signing off on oer-->
            <th scope="col">Senior Rater</th><!--reviewer name , work-->
            <th scope="col">Last OER</th><!--Date-->
            <th scope="col">THRU Date</th><!--Count Down to due date-->
            <th scope="col">Due</th><!--Due-->
            <th scope="col">Type</th><!--Type of OER-->
            <th scope="col">Remarks</th><!--Notes-->
        </tr>
        </thead>
        <tbody>
        <!--This Will be a for eachloop to generate the rows & buttons-->
            <tr>

                <td>1</td>
                <td>CPT</td>
                <td>Tyler</td>
                <td>Elliot</td>
                <td>LtCol.Fulmer</td>
                <td>Col.Meyer</td>
                <td>Billy Boy</td>
                <td>09/09/2020</td>
                <td>100</td>
                <td>03/04/2021</td>
                <td>Magic</td>
                <td>Do Better</td>
                <!--UPDATE AND DELETE BUTTONS-->
                <td>
                    <form action="" method="post">
                        <input type="hidden" name="id" value=""/>
                        <input type="submit" class="button btn btn-primary" name="updateOER" value="Update"/>
                    </form>
                </td>
                <td>
                    <form action="" method="post">
                        <input type="hidden" name="id" value=""/>
                        <input type="submit" class="button btn btn-danger" name="deleteOER" value="Delete"/>
                    </form>
                </td>
            </tr>
        <tr>
            <td>2</td>
            <td>2LT</td>
            <td>Morty</td>
            <td>Smith</td>
            <td>CPT.Summer</td>
            <td>LTCol.Sanchez</td>
            <td>Bird Person</td>
            <td>08/12/2020</td>
            <td>45</td>
            <td>01/03/2021</td>
            <td>Science</td>
            <td>UGHHHHHHHH</td>
            <!--UPDATE AND DELETE BUTTONS-->
            <td>
                <form action="" method="post">
                    <input type="hidden" name="id" value=""/>
                    <input type="submit" class="button btn btn-primary" name="updateOER" value="Update"/>
                </form>
            </td>
            <td>
                <form action="" method="post">
                    <input type="hidden" name="id" value=""/>
                    <input type="submit" class="button btn btn-danger" name="deleteOER" value="Delete"/>
                </form>
            </td>
        </tr>
        </tbody>
    </table>
    <a href="" id="btn_addOER" class="btn btn-success btn-lg float-right">Add OER</a>

</div>
</body>
</html>
<!--
                    <form action="" method="post">
                        <input type="hidden" name="id" value=""/>
                        <input type="submit" class="button btn btn-primary" name="updateOER" value="Update"/>
                    </form>

                    <form action="" method="post">
                        <input type="hidden" name="id" value=""/>
                        <input type="submit" class="button btn btn-danger" name="deleteOER" value="Delete"/>
                    </form>
-->

<!--//create button to update the table
//create button to delete table
//create button to add to table
//ASIA LEVESQUE-->